# Comment to a new issue.
issueOpened: >
  Issue를 생성해 주셔서 감사합니다! 🎉 Hacker님의 열정을 응원해요! 😊
  
  최대한 빠르게 검토한 후 답변 드릴게요!

pullRequestOpened: >
  Pull Request를 생성해 주셔서 감사합니다! 🎉
  
  가이드라인을 준수하셨는지 확인해주세요. 최대한 빠르게 리뷰하겠습니다!